version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Valkyrie.Core" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Valkyrie.Data.Ef" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Valkyrie.Data.Mongo" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Valkyrie.EventBus" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\Valkyrie.Logging" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\Valkyrie.Core" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Valkyrie.Data.Ef" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Valkyrie.Data.Mongo" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Valkyrie.EventBus" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\Valkyrie.Logging" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
#test_script:
#- dotnet test "test\MyFirstUnitTests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
#on_finish: # Run the demo to show that it works
#- dotnet artifacts\ConsoleApplication\ConsoleApplication.dll